In [1]:
import numpy as np 
array_1d=np.array([1,2,3]) 
array_2d=np.array([[1,2,3],[4,5,7]]) 
print("1D Array: ") 
print(array_1d) 
print("2D Array: ") 
print(array_2d)

1D Array: 
[1 2 3]
2D Array: 
[[1 2 3]
 [4 5 7]]


In [2]:
import numpy as np 
array1=np.array([[1,2],[3,4]]) 
array2=np.array([[5,6],[7,8]]) 
add_res=np.add(array1,array2) 
mul_res=np.multiply(array1,array2) 
print("Array 1: ") 
print(array1) 
print("Array 2: ") 
print(array2) 
print("Addition result:") 
print(add_res) 
print("Multiplication result:") 
print(mul_res)

Array 1: 
[[1 2]
 [3 4]]
Array 2: 
[[5 6]
 [7 8]]
Addition result:
[[ 6  8]
 [10 12]]
Multiplication result:
[[ 5 12]
 [21 32]]


In [3]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7]) 
print(arr[1:5])

[2 3 4 5]


In [4]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7]) 
print(arr[4:])

[5 6 7]


In [5]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7]) 
print(arr[-3:-1])

[5 6]


In [6]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print("Sliced array") 
print(arr[1:2,0:1])

Sliced array
[[4]]


In [8]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]]) 
for x in arr: 
 print(x)

[1 2 3]
[4 5 6]


In [9]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]]) 
for x in arr: 
  for y in x: 
    print(y)

1
2
3
4
5
6


In [10]:
import numpy as np 
arr=np.array([[[1,2,3]],[[6,7,8]]]) 
print("3d Array") 
print(arr) 

3d Array
[[[1 2 3]]

 [[6 7 8]]]


In [11]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]]) 
print("Array transpose") 
print(arr.transpose())

Array transpose
[[1 4]
 [2 5]
 [3 6]]


In [12]:
import numpy as np 
random_float=np.random.random() 
random_int=np.random.randint(0,100) 
random_array=np.random.rand(3,3) 
print(random_float) 
print(random_int) 
print(random_array)

0.4634191440375356
35
[[0.22827509 0.57894084 0.00348915]
 [0.29370818 0.56868773 0.70414162]
 [0.84295174 0.00976775 0.05032117]]


In [13]:
import numpy as np 
from scipy.optimize import minimize 
def objective_function(x):return (x-3)**2 
initial_guess=0 
result=minimize(objective_function,initial_guess) 
print("Optimization result:") 
print("Minimum found at:",result.x) 
print("Optimal function value: ",result.fun)

Optimization result:
Minimum found at: [2.99999998]
Optimal function value:  2.5388963550532293e-16


In [14]:
import numpy as np 
from scipy.stats import linregress 
x=np.array([1,2,3,4,5]) 
y=np.array([2,3,4,5,6]) 
slope,intercept,r_value,p_value,std_err=linregress(x,y) 
print("Slope: ",slope) 
print("Intercept: ",intercept) 
print("R-Squared: ",r_value**2)

Slope:  1.0
Intercept:  1.0
R-Squared:  1.0


In [15]:
import numpy as np 
from scipy import linalg 
A=np.array([[1,2],[3,4]]) 
B=np.array([[5,6],[7,8]]) 
c=np.dot(A,B) 
print("Matrix multiplication of A and B: ") 
print(c) 
A_inv=linalg.inv(A) 
print("\nInverse of a matrix A: ") 
print(A_inv) 
evalue,evec=linalg.eig(A) 
print("\nEigen values of matrix A: ") 
print(evalue) 
print("\nEigen vectors of matrix A: ") 
print(evec)

Matrix multiplication of A and B: 
[[19 22]
 [43 50]]

Inverse of a matrix A: 
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigen values of matrix A: 
[-0.37228132+0.j  5.37228132+0.j]

Eigen vectors of matrix A: 
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [18]:
import pandas as pd 
data=pd.read_csv('employee.csv') 
print(data.head())

   emp_id emp_name  salary
0      57     john   85000
1      58    smith   90000
2      59    alice   75000
3      60      bob   80000
4      61     jack   95000


In [21]:
import pandas as pd 
data=pd.read_csv('employee.csv') 
filtered_data=data[data['salary']>80000] 
print(filtered_data)

   emp_id emp_name  salary
0      57     john   85000
1      58    smith   90000
4      61     jack   95000


In [22]:
import pandas as pd 
df1=pd.DataFrame({ 
'ProductID':[1,2,3], 
'ProductName':['Widget A','Widget B','Gadget A'], 
'Category':['Widgets','Widgets','Gadgets'] 
}) 
df2=pd.DataFrame({ 
'ProductID':[1,2,3,4], 
'Price':[19.99,23.99,15.99,18.99], 
'Stock':[150,120,200,100] 
}) 
merged_df=pd.merge(df1,df2,on='ProductID') 
print("Merged Dataframe: ") 
print(merged_df)

Merged Dataframe: 
   ProductID ProductName Category  Price  Stock
0          1    Widget A  Widgets  19.99    150
1          2    Widget B  Widgets  23.99    120
2          3    Gadget A  Gadgets  15.99    200
